#!/usr/bin/env bash

#### Configuration ##############################################################
# Folders
media="$HOME/Music/"
CONFIG_DIR="$HOME/.config/fzp"
HISTORY_DIR="$CONFIG_DIR/history"

# Set default playback interface: one of "tui" or "gui":
# "gui" automatically opens a mpv window on top of fzp, and the extra
# window can be hidden without interrupting playback ("tui" mode) on a,
# key press, while setting this to "tui" will default to not opening a mpv
# window, but can also be toggled during playback, see alt_interface below
interface="tui"

# Set secondary playback interface ('_' key): one of "sixel" or "gui"
# "gui" will open a separate mpv window upon pressing that key, while
# "sixel" will show the mpv interface within the fzp window; the latter
# requires a compatible terminal emulator and mpv built with libsixel
# This option has no effect if the primary interface is "gui", in which
# case the '_' key will always switch to "tui" (sixel switching not supported)
alt_interface="gui"

# Use supplied lua script to format output, recommended
luascript="yes"

#### End of configuration #######################################################

# Variables
if [ "$luascript" = "yes" ]; then
    script="--script=$CONFIG_DIR/fzp.lua"
fi
BASE_PATH=""
show_help=false

if [[ ! -d "$HISTORY_DIR" ]]; then
    mkdir -p "$HISTORY_DIR"
fi

# Define text status format
text_status="'\${?pause==no:$(printf \\033[1\;5\;35m)▶ }\${?pause==yes:$(printf \\033[1\;5\;33m)⏸ }$(printf \\033[25m)\${percent-pos}% [\${time-pos}/\${duration}\${!speed==1: × \${speed}}]$(printf \\033[0m) $(printf \\033[1m)\${filename/no-ext}$(printf \\033[0m) \${?mute==yes:| $(printf \\033[36m)muted}$(printf \\033[0m) '"

mpv_opts_base="--no-config --ao=pulse --osd-level=0 --profile=sw-fast $script --cover-art-auto=no --watch-later-dir=$HOME/.local/state/mpv/watch_later --save-position-on-quit --script-opts=osc-visibility=always,tick_delay=1 --msg-level=all=error,statusline=status --term-status-msg=$text_status"

# Function to display help menu
show_help() {
    echo "fzp - A terminal audio player based on fzf and mpv, featuring fuzzy finding,"
    echo "sixel graphics, playlists and history for resuming playback (i.e., audiobooks)."
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  -d, --dirs, --directories     List directories only (default)"
    echo "  -f, --files                   List audio files recursively with directories"
    echo "  -c, --continue, --history     Resume playback from history"
    echo "  -i, --interface <value>       Primary playback interface: tui (default) or gui"
    echo "  -a, --alt-interface <value>   Set alternate interface if primary is tui: gui (default) or sixel"
    echo "  -p, --path <path>             PSet path to media (default: ~/Music)"
    echo "  -h, --help                    Show this help message and exit"
    echo ""
}

# Check dependencies
check_dependencies() {
    local dependencies=("fzf>=0.54.0" "mpv>=0.38.0" "soxi" "fd")
    local missing_dependencies=()

    for dep in "${dependencies[@]}"; do
        local name="${dep%%>=*}"
        local version="${dep##*>=}"
        if ! command -v "$name" &> /dev/null; then
            missing_dependencies+=("$dep")
        elif [[ "$dep" == *">="* ]]; then
            local installed_version
            case "$name" in
                fzf)
                    installed_version=$(fzf --version | head -n 1)
                    ;;
                mpv)
                    installed_version=$(mpv --version | head -n 1 | awk '{print $2}')
                    ;;
                soxi)
                    installed_version=$(soxi --version | head -n 1 | awk '{print $3}')
                    ;;
                fd)
                    installed_version=$(fd --version | head -n 1 | awk '{print $2}')
                    ;;
            esac
            if [[ "$installed_version" < "$version" ]]; then
                missing_dependencies+=("$dep")
            fi
        fi
    done

    if [ ${#missing_dependencies[@]} -ne 0 ]; then
        echo -e "\033[31mError:\033[0m ${missing_dependencies[@]} not found or outdated."
        exit 1
    fi
}

# Function to parse command-line arguments
parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            -h|--help)
                show_help
                exit 0
                ;;
            -c|--continue|--history)
                mode="history"
                ;;
            -f|--files)
                mode="files"
                ;;
            -d|--dirs|--directories)
                mode="dirs"
                ;;
            -i|--interface)
                shift
                if [ -z "$1" ]; then
                    echo "Error: --interface requires a value among (tui, gui)."
                    exit 1
                fi
                interface="$1"  # Set the primary_interface variable
                ;;
            -a|--alt-interface)
                shift
                if [ -z "$1" ]; then
                    echo "Error: --alt-interface requires a value among (sixel, gui)."
                    exit 1
                fi
                alt_interface="$1"  # Set the secondary_interface variable
                ;;
            -p|--path)
                shift
                if [ -z "$1" ]; then
                    echo "Warning: --path requires a value. Using default."
                    path=$(realpath "$media")
                else
                    path=$(realpath "$1")
                    BASE_PATH="$path"
                fi
                ;;
            *)
                echo "Error: Invalid option $1"
                show_help
                exit 1
                ;;
        esac
        shift
    done

    # Set default path if not provided
    if [ -z "$path" ]; then
        path=$(realpath "$media")
        BASE_PATH="$path"
    fi
}

# Configure mpv interface based on the specified interface in configuration or command line
configure_mpv_interface() {
    # Priority to runtime arguments over configuration
    if [[ -n "$alt_interface" ]]; then
	secondary_interface="$alt_interface"
    fi
    
    case "$interface" in
        tui)
	    if [[ "$secondary_interface" == "gui" ]]; then
	        secondary_interface=""
		mpvui="--vo=$secondary_interface --no-video --input-conf='memory://_ cycle vid'"
	    elif [[ "$secondary_interface" == "sixel" ]]; then
		mpvui="--vo=$secondary_interface --no-video --input-conf='memory://_ cycle-values term-status-msg $dummy_text ${text_status//\'/\"}; cycle vid'"
	    else
		echo "Error: Invalid value for --secondary-interface. Use sixel or gui."
		exit 1
	    fi
            ;;
        gui)
	    if [[ -n "$secondary_interface" && "$secondary_interface" != "tui" ]]; then
		echo "Warning: Setting alternate interface has no use unless the primary is set to 'tui'."
		sleep 1
	    else
		mpvui="--input-conf='memory://_ cycle vid'"
	    fi
            ;;
        *)
            echo "Error: Invalid value for --interface. Use tui or gui."
            exit 1
            ;;
    esac
}

# Function to play selected files
# We have to use an eval of $play_files here because this allows using double quotes; if we just use
# a shell function, the $mpv_opts and $mpvui are not correctly expanded, even with double quotes
play_files() {
    eval "mpv $mpv_opts_base $mpvui $@"
}

# Basic file browser with directory and file preview
fdfun() {
    fd $filter --min-depth 1 --max-depth 1 -L $filter2 --color=always | sort $reverse
}

# Main function
main() {
    echo "$HISTORY_DIR" > /tmp/fzp-dirs
    cd "$1" 2>/dev/null || { echo "Invalid media directory: '$1'"; exit 1; }
    echo "$1" >> /tmp/fzp-dirs

    if [[ ! -f /tmp/fzp-playlist ]]; then
        cat /dev/null > /tmp/fzp-playlist
    fi
    cat /dev/null > /tmp/fzp-pos
    echo "on" > /tmp/fzp-preview

    while :; do

	# Keep a copy of the temporary playlist in history even after reboots
	# Check if the files in /tmp and history directory exist
	if [[ ! -f "$HISTORY_DIR"/tmp ]]; then
	    cat /dev/null > "$HISTORY_DIR"/tmp
	fi
	if [[ ! -f /tmp/fzp-playlist ]]; then
	    # If it doesn't exist, create it based on the file in ~/.config
	    ln -s "$HISTORY_DIR/tmp" /tmp/fzp-playlist
	fi

	if [[ -z "$dir" ]]; then
            dir="$1"
        elif [[ -f "$dir" ]]; then
            dir="$(dirname "$dir")"
        fi
        
        if [[ "$mode" == "history" ]]; then
            dir="$HISTORY_DIR"
            folder=""
            reverse="--reverse"
        else
            folder="$(basename "$dir") > "
            reverse=""
        fi 
        cd "$dir"
       
        clear

        selection=$(fdfun \
                | fzf --query="${tmp}" \
                      --prompt='# ' \
                      --ansi \
                      --extended \
                      --no-border \
                      --delimiter='/' \
                      --layout=reverse-list \
                      --multi \
		      --marker='+' \
                      --cycle \
                      --sync \
                      --prompt="$(printf '%s\033[2m%s\033[0m' "$fzf_prompt" "$folder")" \
                      --header="$fzf_header" \
                      --preview="$fzf_preview" \
                      --preview-window="$fzf_preview_window" \
                      --with-nth="$fzf_withnth.." \
                      --margin='1,2,1,2' \
                      --color='16,gutter:-1' \
                      --info-command='echo -e "\x1b[33;1m$FZF_POS\x1b[m/$FZF_INFO"' \
                      --bind="start:pos($last)" \
                      --bind='enter:execute-silent(echo "$FZF_POS" >> /tmp/fzp-pos)' \
                      --bind='enter:+execute(echo "play" > /tmp/fzp-arg)+accept' \
                      --bind='?:execute(echo "help" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-p:execute(echo "preview-toggled" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-h:execute(echo "history" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-d:execute(echo "dirs" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-f:execute(echo "files" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-e:execute(echo "edit" > /tmp/fzp-arg)+accept' \
                      --bind='del:execute(echo "delete" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-a:execute(echo "add" > /tmp/fzp-arg)+accept' \
		      --bind='ctrl-j:execute(echo "addplay" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-r:execute(echo "rename" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-s:execute(echo "save" > /tmp/fzp-arg)+accept' \
                      --bind='left:execute(echo "cdup" > /tmp/fzp-arg)+accept' \
                      --bind='right:execute-silent(echo "$FZF_POS" >> /tmp/fzp-pos)' \
                      --bind='right:+execute(echo "cddown" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-x:execute(echo "audio-preview" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-c:execute(echo "preview-toggled" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-q:execute(echo "quit" > /tmp/fzp-arg)+cancel' \
                      --bind='esc:execute(echo "quit" > /tmp/fzp-arg)+cancel')

        if [[ -f "/tmp/fzp-arg" ]]; then
            arg=$(cat /tmp/fzp-arg)
            rm /tmp/fzp-arg
        else
            arg="ls -lah"
        fi

        if [[ -f "/tmp/fzp-last" ]]; then
            last_selection=$(cat /tmp/fzp-last)
            rm /tmp/fzp-last
        fi

        if ! [[ -v "$selection" ]]; then
            clear
            case "$arg" in
                history)
                    mode="history"
                    filter="--type f"
                    filter2=". $HISTORY_DIR"
                    fzf_prompt='History > '
                    fzf_withnth="-1"
                    if [[ $(cat /tmp/fzp-preview) == "on" ]]; then 
                        fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev"
                    fi
                    fzf_preview_window="65%,border-left,nowrap"
                    fzf_header='
? Help

'
                    continue
                    ;;
                dirs)
                    mode="dirs"
		    if [[ "$dir" == "$HISTORY_DIR" ]]; then
			dir="$path"
		    else
			dir="$dir"
		    fi
                    filter='--type d'
                    filter2="."
                    fzf_prompt="Dirs > "
                    fzf_withnth="-3"
                    if [[ $(cat /tmp/fzp-preview) == "on" ]]; then 
                        fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'"
                    fi
                    fzf_preview_window="45%,border-left,nowrap"
                    fzf_header='
? Help

'
                    continue
                    ;;
                files)
                    mode="files"
		    if [[ "$dir" == "$HISTORY_DIR" ]]; then
			dir="$path"
		    else
			dir="$dir"
		    fi
                    filter='--type f'
                    filter2='--max-depth 8 -e mp3 -e m4a -e flac -e wav -e ogg'
                    fzf_prompt='Files > '
                    fzf_withnth="-3"
                    if [[ $(cat /tmp/fzp-preview) == "on" ]]; then 
                        fzf_preview="soxi {}"
                    fi
                    fzf_preview_window="45%,border-left,nowrap"
                    fzf_header='
? Help

'
                    continue
                    ;;
                play)
                    # fd the list of audio files in subdirectories of the selected folder and list them with their full path in /tmp/fzp-playlist
                    # Then run play_files on that list
                    if [[ "$mode" == "history" ]]; then
                        cp "$selection" /tmp/fzp-playlist 2>/dev/null
		    elif [[ "$mode" == "files" ]]; then
			echo "$(realpath "$selection")" > /tmp/fzp-playlist
                    elif [[ "$mode" == "dirs" ]]; then
                        fd .  --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg "$(realpath "$selection")" | sort > /tmp/fzp-playlist
                    fi
                    last="$(tail -n 1 /tmp/fzp-pos)"
                    head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-po
                    play_files --playlist=/tmp/fzp-playlist
                    ;;
		save)
                    # Save current /tmp/fzp-playlist playlist to $HISTORY_DIR/YYYYMMDD_<number of lines in the file>_tracks
                    local datetime=$(date +%Y%m%d_%H%M%S)
                    if [[ "$mode" == "history" ]]; then
                        cp "$selection" /tmp/fzp-playlist
		    elif [[ "$mode" == "files" ]]; then
			echo "$(realpath "$selection")" > /tmp/fzp-playlist
                    elif [[ "$mode" == "dirs" ]]; then
                        fd .  --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg "$(realpath "$selection")" | sort > /tmp/fzp-playlist
                    fi
                    last="$(tail -n 1 /tmp/fzp-pos)"
                    head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-pos
                    cp /tmp/fzp-playlist "$HISTORY_DIR/${datetime}"
                    play_files --playlist=/tmp/fzp-playlist
                    ;;
                addplay)
                    # Similar to "play" but append to /tmp/fzp-playlist without relaunching mpv, i.e., add to queue
                    if [[ "$mode" == "history" ]]; then
                        cat "$selection" >> /tmp/fzp-playlist
		    elif [[ "$mode" == "files" ]]; then
			echo "$(realpath "$selection")" >> /tmp/fzp-playlist
                    else
                        fd . --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg "$(realpath "$selection")" | sort >> /tmp/fzp-playlist
                    fi
		    play_files --playlist=/tmp/fzp-playlist
                    ;;
add)
    # Similar to "play" but append to /tmp/fzp-playlist without relaunching mpv, i.e., add to queue
    if [[ "$mode" == "history" ]]; then
        cat "$selection" >> /tmp/fzp-playlist
    elif [[ "$mode" == "files" ]]; then
        IFS=$'\n' [[ -n "$selection" ]] && echo "$(realpath "$dir/${selection[@]}")" >> /tmp/fzplaylist & exit
    else
        while IFS= read -r file; do
            fd . --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg "$(realpath "$file")" | sort >> /tmp/fzp-playlist
        done <<< "$selection"
    fi
    ;;
                edit)
                    # Invoke $EDITOR on the corresponding $HISTORY_DIR/YYYYMMDD_folderdepth2>folderdepth3 file
                    # Alternatively, revert to vim
                    # This option is only available while in History fzf prompt
                    if [[ "$mode" == "history" ]]; then
                        eval "${EDITOR:-vim} \"$(realpath "$selection")\""
                    fi
                    ;;
		rename)
		    # Rename or make a copy of the corresponding $HISTORY_DIR/YYYYMMDD_folderdepth2>folderdepth3 file
		    # This option is only available while in History fzf prompt
		    if [[ "$mode" == "history" ]]; then
			current_name=$(basename "$selection")
			printf "\033[2B\033[2m(same name to make a copy, none to abort)\033\0m"
			read -r -e -i "$current_name" -p "$(echo -e "\033[0;0H\033[2mRename '$current_name' to:\033[0m ")" n

			# Check if the new name is valid
			if [[ -z "$n" ]]; then
			    echo -e "\033[31m\n\n\nError:\033[0m Name cannot be empty." && sleep 1
			elif [[ "$n" == *"../"* || "$n" == *"/.."* ]]; then
			    echo -e "\033[31m\n\n\nError:\033[0m Invalid name. Escalating into upper folders is not allowed." && sleep 1
			else
			    new_path="$(realpath -m "$(dirname "$selection")/$n")"

			    if [[ "$new_path" == "$HISTORY_DIR"* ]]; then
				if [[ "$n" == "$current_name" ]]; then
				    datetime=$(date +%Y%m%d_%H%M%S)
				    copy_path="${new_path}_${datetime}_copy"
				    cp -i -v "$selection" "$copy_path"
				else
				    mv -i -v "$selection" "$new_path"
				fi
			    else
				echo -e "\033[31m\n\n\nError:\033[0m Invalid destination path." && sleep 1
			    fi
			fi
		    fi
		    ;;
		delete)
                    # Delete the selected file from history
                    # This option is only available while in History fzf prompt
                    if [[ "$mode" == "history" ]]; then
                        rm -i "$(realpath "$selection")"
                    fi
                    ;;
		cdown)
                    # cd into selected directory and relaunch main()
                    if [[ "$mode" == "dirs" && -n "$(fd . --type d --max-depth 1 "$selection")" ]]; then
                        dir="$(realpath "$selection")"
                        last=""
                    elif [[ "$mode" != "dirs" && -f "$selection" ]]; then
                        from_dir="$dir"
                        dir="$(dirname "$(realpath "$selection")")"
                        last="" # Would be good to calculate the position of the track in the folder here, but it is not "$(tail -n 1 /tmp/fzp-pos)" because this was calculated from the Files view with all brother folders listed
                    elif [[ "$mode" == "dirs" && -z "$(fd . --type d --max-depth 1 "$selection")" ]]; then
                        last="$(tail -n 1 /tmp/fzp-pos)"
                        head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-pos
                    elif [[ "$mode" != "dirs" && -z "$(fd . --type d --max-depth 1)" ]]; then
                        head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-pos
                    elif [[ "$mode" != "dirs" ]]; then
                        from_dir="$dir"
                        dir="$(realpath "$(dirname "$selection")")"
                        last=""
                    fi
                    continue
                    ;;
                cdup)
                    # cd into parent directory and relaunch main()
                    par_dir="$(realpath "$(dirname "$dir")")"
                    if [[ -n "$par_dir" && "$mode" != "files" && "$(realpath "$dir")" != "$(realpath "$media")" ]]; then
                        if [[ "$par_dir" == "$BASE_PATH" || "$par_dir" == "${BASE_PATH}"/* ]]; then
                            dir="$par_dir"
                            last="$(tail -n 1 /tmp/fzp-pos)"
                        else
                            echo "Already at the base path, cannot move up further."
                        fi
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$dir")" != "$(realpath "$media")" ]]; then
                        if [[ "$par_dir" == "$BASE_PATH" || "$par_dir" == "${BASE_PATH}"/* ]]; then
                            case "$dir" in
                                "$from_dir")
                                    dir="$media"
                                    last="" ;;
                                *)
                                    dir="$from_dir"
                                    last="$(tail -n 1 /tmp/fzp-pos)" ;;
                            esac
                        else
                            echo "Already at the base path, cannot move up further."
                        fi
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$dir")" == "$(realpath "$media")" ]]; then
                        last=""
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$from_dir")" == "$(realpath "$media")" ]]; then
                        dir="$media"
                        last="$(tail -n 1 /tmp/fzp-pos)"
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$from_dir")" == "$(realpath "$media")"/* && "$(realpath "$from_dir")" == "$(realpath "$dir")" ]]; then
                        dir="$(realpath "$(dirname "$dir")")"
                        last=""
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$from_dir")" == "$(realpath "$media")"/* && "$(realpath "$from_dir")" != "$(realpath "$dir")" ]]; then
                        dir="$from_dir"
                        last="$(tail -n 1 /tmp/fzp-pos)"
                    elif [[ -n "$par_dir" && "$(realpath "$par_dir")" == "$(realpath "$media")"/* && "$(realpath "$par_dir")" != "$(realpath "$dir")" ]]; then
                        dir="$par_dir"
                        last="$(tail -n 1 /tmp/fzp-pos)"
                    fi
                    head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-pos
                    continue
                    ;;
                preview-toggled)
                    # Toggle the preview panel on/off
                    if [[ $(cat /tmp/fzp-preview) == "on" || $(cat /tmp/fzp-preview) == "audio-on" ]]; then 
                        echo "off" > /tmp/fzp-preview
                        fzf_preview=""
                        pkill mpv
                    else
                        echo "on" > /tmp/fzp-preview
                        case "$mode" in
                            history)
                                fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev" ;;
                            files)
                                fzf_preview="soxi {}" ;;
                            *)
                                fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'" ;;
                        esac
                    fi   
                    continue
                    ;;
                audio-preview)
                    # Enable/disable audio preview
                    if [[ "$audio_preview" == "false" ]]; then
                        fzf_preview='echo -e "\033[5;1m♫\033[25;0m AUDIO PREVIEW\n\n\033[2mPress C-x to stop\033[0m" && sleep 0.2 && mpv --no-config --no-video --really-quiet {}'
                        audio_preview=true
                        echo "audio-on" > /tmp/fzp-preview
                    else
                        audio_preview=false
                        echo "audio-off" > /tmp/fzp-preview
                        case "$(cat /tmp/fzp-preview)" in
                            "on")
                                case "$mode" in
                                    history)
                                        fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev" ;;
                                    files)
                                        fzf_preview="soxi {}" ;;
                                    *)
                                        fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'" ;;
                                esac
                                ;;
                            "off")
                                fzf_preview=""
                                ;;
                            "audio-on")
                                ;;
                            "audio-off")
                                case "$show_help" in
                                    false)
                                    ;;
                                esac
                        esac
                    fi
                    continue
                    ;;
		help)
		    # Toggle help display
		    if [[ "$show_help" == "false" ]]; then
			help_text='\033[34;1mKeybindings\033[0m

  General

  \033[1;7m abc \033[0;27m fuzzy search
  \033[1;7m ← → \033[0;27m exit/enter directory
  \033[1;7m ↑ ↓ \033[0;27m move cursor up/down
  \033[1;7m C-q \033[0;27m clear search or quit if none

  Mode

  \033[1;7m C-d \033[0;27m show directories only
  \033[1;7m C-f \033[0;27m show files recursively
  \033[1;7m C-h \033[0;27m show history (saved playlists)

  Playback queue

  \033[1;7m Ent \033[0;27m send to tmp playlist & play
  \033[1;7m C-s \033[0;27m save to new playist & play
  \033[1;7m C-j \033[0;27m enqueue to tmp playlist & resume
  \033[1;7m C-a \033[0;27m enqueue to tmp playlist

  Preview

  \033[1;7m C-p \033[0;27m toggle preview panel
  \033[1;7m C-x \033[0;27m enable audio preview
  \033[1;7m C-c \033[0;27m disable audio preview
  \033[1;7m   ? \033[0;27m toggle help

  History

  \033[1;7m C-e \033[0;27m edit playlist
  \033[1;7m C-r \033[0;27m rename playlist
  \033[1;7m Del \033[0;27m delete playlist

'
			fzf_preview="printf '$help_text'"
			show_help=true
		    else
			show_help=false
			case "$(cat /tmp/fzp-preview)" in
			    "on")
				case "$mode" in
				    history)
					fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev" ;;
				    files)
					fzf_preview="soxi {}" ;;
				    *)
					fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'" ;;
				esac
				;;
			    "off")
				fzf_preview=""
				;;
			    "audio-on")
				fzf_preview='echo -e "\033[5;1m♫\033[25;0m AUDIO PREVIEW\n\n\033[2mPress C-x to stop\033[0m" && sleep 0.2 && mpv --no-config --no-video --really-quiet {}'
				;;
			esac
		    fi
		    ;;
                quit)
                    # Quit the program
                    pkill -P $$
		    clear
                    return
                    ;;
                *)
                    continue
                    ;;
            esac
        fi
    done
}   

# Main script logic
check_dependencies
clear
parse_args "$@"
configure_mpv_interface

case "$mode" in
    history)
        filter="--type f"
        filter2="."
        fzf_prompt='History > '
        fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev"
        fzf_preview_window="45%,border-left,nowrap"
        fzf_header='
? Help

'
        main "$HISTORY_DIR"
        ;;
    files)
        filter='--type f'
        filter2='--max-depth 8 -e mp3 -e m4a -e flac -e wav -e ogg'
        fzf_prompt='Files > '
        fzf_preview="soxi {}"
        fzf_preview_window="45%,border-left,nowrap"
        fzf_header='
? Help

'
        main "$path"
        ;;
    ""|dirs)
        mode="dirs"
        filter='--type d'
        filter2="."
        fzf_prompt="Dirs > "
        fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'"
        fzf_preview_window="45%,border-left,nowrap"
        fzf_header='
? Help

'
        main "$path"
        ;;
esac

