#!/usr/bin/env bash

#### Configuration ##############################################################
# Folders
media="$HOME/Music/"
CONFIG_DIR="$HOME/.config/fzp"
HISTORY_DIR="$CONFIG_DIR/history"

# Set default playback interface: one of "tui" or "gui":
# "gui" automatically opens a mpv window on top of fzp, and the extra
# window can be hidden without interrupting playback ("tui" mode) on a key
# press, while setting this to "tui" will default to not opening a mpv
# window, but can also be toggled during playback, see alt_interface below
interface="tui"

# Set secondary playback interface ('_' key): one of "sixel" or "gui"
# "gui" will open a separate mpv window upon pressing that key, while
# "sixel" will show the mpv interface within the fzp window; the latter
# requires a compatible terminal emulator and mpv built with libsixel
# This option has no effect if the primary interface is "gui", in which
# case the '_' key will always switch to "tui" (sixel switching not supported)
alt_interface="gui"

#### End of configuration #######################################################

# Variables
show_help=false
BASE_PATH=""
last=""

if [[ ! -d "$HISTORY_DIR" ]]; then
    mkdir -p "$HISTORY_DIR"
fi

# Define text status format
text_status="'\${?pause==no:$(printf \\033[1\;5\;35m)▶ }\${?pause==yes:$(printf \\033[1\;5\;33m)⏸ }$(printf \\033[25m)\${percent-pos}% [\${time-pos}/\${duration}\${!speed==1: × \${speed}}]$(printf \\033[0m) $(printf \\033[1m)\${filename/no-ext}$(printf \\033[0m) \${?mute==yes:| $(printf \\033[36m)muted}$(printf \\033[0m) '"

mpv_opts_base="--no-config --ao=pulse --osd-level=0 --profile=sw-fast --script=$CONFIG_DIR/fzp.lua --cover-art-auto=no --watch-later-dir=$HOME/.local/state/mpv/watch_later --save-position-on-quit --script-opts=osc-visibility=always,tick_delay=1 --msg-level=all=error,statusline=status --term-status-msg=$text_status"

# Function to display help menu
show_help() {
    echo "fzp - A terminal audio player based on fzf and mpv, supporting fuzzy finding,"
    echo "sixel graphics, playlists and history for resuming playback (i.e., audiobooks)."
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  -d, --dirs, --directories     List directories only (default)"
    echo "  -f, --files                   List audio files recursively with directories"
    echo "  -c, --continue, --history     Resume playback from history/playlists"
    echo "  -i, --interface <value>       Primary playback interface: tui (default) or gui"
    echo "  -a, --alt-interface <value>   Alternate interface if primary is tui: gui (default) or sixel"
    echo "  -p, --path <path>             Path to media (default: ~/Music)"
    echo "  -h, --help                    Show this help message and exit"
    echo ""
}

# Check dependencies
check_dependencies() {
    local dependencies=("fzf>=0.54.0" "mpv>=0.38.0" "soxi" "fd")
    local missing_dependencies=()

    for dep in "${dependencies[@]}"; do
        local name="${dep%%>=*}"
        local version="${dep##*>=}"
        if ! command -v "$name" &> /dev/null; then
            missing_dependencies+=("$dep")
        elif [[ "$dep" == *">="* ]]; then
            local installed_version
            case "$name" in
                fzf)
                    installed_version=$(fzf --version | head -n 1)
                    ;;
                mpv)
                    installed_version=$(mpv --version | head -n 1 | awk '{print $2}')
                    ;;
                soxi)
                    installed_version=$(soxi --version | head -n 1 | awk '{print $3}')
                    ;;
                fd)
                    installed_version=$(fd --version | head -n 1 | awk '{print $2}')
                    ;;
            esac
            if [[ "$installed_version" < "$version" ]]; then
                missing_dependencies+=("$dep")
            fi
        fi
    done

    if [ ${#missing_dependencies[@]} -ne 0 ]; then
        echo -e "\033[31mError:\033[0m ${missing_dependencies[@]} not found or outdated."
        exit 1
    fi
}

# Function to parse command-line arguments
parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            -h|--help)
                show_help
                exit 0
                ;;
            -c|--continue|--history)
                mode="history"
                ;;
            -f|--files)
                mode="files"
                ;;
            -d|--dirs|--directories)
                mode="dirs"
                ;;
            -i|--interface)
                shift
                if [ -z "$1" ]; then
                    echo "Error: --interface requires a value among (tui, gui)."
                    exit 1
                fi
                interface="$1"  # Set the primary_interface variable
                ;;
            -a|--alt-interface)
                shift
                if [ -z "$1" ]; then
                    echo "Error: --alt-interface requires a value among (sixel, gui)."
                    exit 1
                fi
                alt_interface="$1"  # Set the secondary_interface variable
                ;;
            -p|--path)
                shift
                if [ -z "$1" ]; then
                    echo -e "\033[31mWarning:\033[0m --path requires a value. Using default."
		    sleep 1
                    path=$(realpath "$media")
                else
                    path=$(realpath "$1")
                    BASE_PATH="$path"
                fi
                ;;
            *)
                echo "Error: Invalid option $1"
                show_help
                exit 1
                ;;
        esac
        shift
    done

    # Set default path if not provided
    if [ -z "$path" ]; then
        path=$(realpath "$media")
        BASE_PATH="$path"
    fi
}

# Configure mpv interface based on the specified interface in configuration or command line
configure_mpv_interface() {
    # Priority to runtime arguments over configuration
    if [[ -n "$alt_interface" ]]; then
	secondary_interface="$alt_interface"
    fi
    
    case "$interface" in
        tui)
	    if [[ "$secondary_interface" == "gui" ]]; then
	        secondary_interface=""
		mpvui="--vo=$secondary_interface --no-video --input-conf='memory://_ cycle vid'"
	    elif [[ "$secondary_interface" == "sixel" ]]; then
		mpvui="--vo=$secondary_interface --no-video --input-conf='memory://_ cycle-values term-status-msg $dummy_text ${text_status//\'/\"}; cycle vid'"
	    else
		echo "Error: Invalid value for --secondary-interface. Use sixel or gui."
		exit 1
	    fi
            ;;
        gui)
	    if [[ -n "$secondary_interface" && "$secondary_interface" != "tui" ]]; then
	        echo -e "\033[31mWarning:\033[0m Setting alternate interface has no use unless the primary is set to 'tui'."
		sleep 1
	    else
		mpvui="--input-conf='memory://_ cycle vid'"
	    fi
            ;;
        *)
            echo "Error: Invalid value for --interface. Use tui or gui."
            exit 1
            ;;
    esac
}

# Function to play selected files
# We have to use an eval of $play_files here because this allows using double quotes; if we just use
# a shell function, the $mpv_opts and $mpvui are not correctly expanded, even with double quotes
play_files() {
    eval "mpv $mpv_opts_base $mpvui $@"
}

# Basic file browser with directory and file preview
fdfun() {
    fd $filter --min-depth 1 --max-depth 1 -L $filter2 --color=always | sort $reverse
}

# Main function
main() {
    echo "$HISTORY_DIR" > /tmp/fzp-dirs
    cd "$1" 2>/dev/null || { echo "Invalid media directory: '$1'"; exit 1; }
    echo "$1" >> /tmp/fzp-dirs

    # Keep a copy of the temporary playlist in history even after reboots
    # Check if the files in /tmp and history directory exist
    if [[ ! -f "$HISTORY_DIR"/tmp ]]; then
	cat /dev/null > "$HISTORY_DIR"/tmp
    fi
    if [[ ! -f /tmp/fzp-playlist ]]; then
	# If it doesn't exist, create it based on the file in ~/.config
	ln "$HISTORY_DIR"/tmp /tmp/fzp-playlist
    fi

    cat /dev/null > /tmp/fzp-pos
    echo "on" > /tmp/fzp-preview

    while :; do

	if [[ -z "$dir" ]]; then
            dir="$1"
        elif [[ -f "$dir" ]]; then
            dir="$(dirname "$dir")"
        fi
        
        if [[ "$mode" == "history" ]]; then
            dir="$HISTORY_DIR"
            folder=""
            reverse="--reverse"
        else
            folder="$(basename "$dir") > "
            reverse=""
        fi 
        cd "$dir"
       
        clear

        selection=$(fdfun \
                | fzf --query="${tmp}" \
                      --prompt='# ' \
                      --ansi \
                      --extended \
                      --no-border \
                      --delimiter='/' \
                      --layout=reverse-list \
                      $multi \
		      --marker='+' \
                      --cycle \
                      --sync \
                      --prompt="$(printf '%s\033[2m%s\033[0m' "$fzf_prompt" "$folder")" \
                      --header="$fzf_header" \
                      --preview="$fzf_preview" \
                      --preview-window="$fzf_preview_window" \
                      --with-nth="$fzf_withnth.." \
                      --margin='1,2,1,2' \
                      --color='16,gutter:-1' \
                      --info-command='echo -e "\x1b[33;1m$FZF_POS\x1b[m/$FZF_INFO"' \
                      --bind="start:pos($last)" \
                      --bind='enter:execute-silent(echo "$FZF_POS" >> /tmp/fzp-pos)' \
                      --bind='enter:+execute(echo "play" > /tmp/fzp-arg)+accept' \
                      --bind='?:execute(echo "help" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-p:execute(echo "preview-toggled" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-h:execute(echo "history" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-d:execute(echo "dirs" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-f:execute(echo "files" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-e:execute(echo "edit" > /tmp/fzp-arg)+accept' \
                      --bind='del:execute(echo "delete" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-a:execute(echo "add" > /tmp/fzp-arg)+accept' \
		      --bind='ctrl-j:execute(echo "addplay" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-r:execute(echo "rename" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-s:execute(echo "save" > /tmp/fzp-arg)+accept' \
                      --bind='left:execute(echo "cdup" > /tmp/fzp-arg)+accept' \
                      --bind='right:execute-silent(echo "$FZF_POS" >> /tmp/fzp-pos)' \
                      --bind='right:+execute(echo "cddown" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-x:execute(echo "audio-preview" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-c:execute(echo "preview-toggled" > /tmp/fzp-arg)+accept' \
                      --bind='ctrl-q:execute(echo "quit" > /tmp/fzp-arg)+cancel' \
		      --bind='up:up+execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
		      --bind='down:down+execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
		      --bind='left-click:execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
		      --bind='tab:toggle+down+execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
		      --bind='btab:toggle+up+execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
		      --bind='ctrl-o:execute-silent(xdg-open {})' \
		      --bind='ctrl-\:execute-silent(echo "run" > /tmp/fzp-arg)+accept' \
		      --bind='$:execute-silent(echo "shell" > /tmp/fzp-arg)+accept' \
                      --bind='esc:execute(echo "quit" > /tmp/fzp-arg)+cancel')


        if [[ -f "/tmp/fzp-arg" ]]; then
            arg=$(cat /tmp/fzp-arg)
            rm /tmp/fzp-arg
        fi

        if [[ -f "/tmp/fzp-last" ]]; then
            last_selection=$(cat /tmp/fzp-last)
            rm /tmp/fzp-last
        fi

        if ! [[ -v "$selection" ]]; then
            clear
            case "$arg" in
                history)
                    mode="history"
		    multi="--no-multi"
		    last=""
                    filter="--type f"
                    filter2=". $HISTORY_DIR"
                    fzf_prompt='History > '
                    fzf_withnth="-1"
                    if [[ $(cat /tmp/fzp-preview) == "on" ]]; then 
                        fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev"
                    fi
                    fzf_preview_window="65%,border-left,nowrap"
                    fzf_header='
? Help

'
                    continue
                    ;;
                dirs)
                    mode="dirs"
		    multi="--multi"
		    if [[ "$dir" == "$HISTORY_DIR" ]]; then
			dir="$path"
		    else
			dir="$dir"
		    fi
                    filter='--type d'
                    filter2="."
                    fzf_prompt="Dirs > "
                    fzf_withnth="-3"
                    if [[ $(cat /tmp/fzp-preview) == "on" ]]; then 
                        fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'"
                    fi
                    fzf_preview_window="45%,border-left,nowrap"
                    fzf_header='
? Help

'
                    continue
                    ;;
                files)
                    mode="files"
		    multi="--multi"
		    if [[ "$dir" == "$HISTORY_DIR" ]]; then
			dir="$path"
		    else
			dir="$dir"
		    fi
                    filter='--type f'
                    filter2='--max-depth 8 -e mp3 -e m4a -e flac -e wav -e ogg -e ape'
                    fzf_prompt='Files > '
                    fzf_withnth="-3"
                    if [[ $(cat /tmp/fzp-preview) == "on" ]]; then 
                        fzf_preview="soxi {}"
                    fi
                    fzf_preview_window="45%,border-left,nowrap"
                    fzf_header='
? Help

'
                    continue
                    ;;
                play)
                    # fd the list of audio files in subdirectories of the selected folder and list them with their full path in /tmp/fzp-playlist
                    # Then run play_files on that list
                    if [[ "$mode" == "history" ]]; then
                        cp "$selection" /tmp/fzp-playlist 2>/dev/null
		    elif [[ "$mode" == "files" ]]; then
			cat /dev/null > /tmp/fzp-playlist
			while IFS= read -r line; do
			    # Append the contents of each line to /tmp/fzp-playlist
			    echo "$(realpath "$line")" >> /tmp/fzp-playlist
			done <<< "$(echo "$selection")"
                    elif [[ "$mode" == "dirs" ]]; then
			cat /dev/null > /tmp/fzp-playlist
			while IFS= read -r line; do
			    # Append the contents of each line to /tmp/fzp-playlist
			    fd .  --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg -e ape "$(realpath "$line")" | sort >> /tmp/fzp-playlist
			done <<< "$(echo "$selection")"
                    fi
                    last="$(tail -n 1 /tmp/fzp-pos)"
                    head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-pos
                    play_files --playlist=/tmp/fzp-playlist
                    ;;
		save)
		    # Save current /tmp/fzp-playlist playlist to $HISTORY_DIR/YYYYMMDD_HHMMSS
		    local datetime=$(date +%Y%m%d_%H%M%S)
		    if [[ "$mode" == "history" ]]; then
			cp "$selection" /tmp/fzp-playlist 2>/dev/null
		    elif [[ "$mode" == "files" ]]; then
			cat /dev/null > /tmp/fzp-playlist
			while IFS= read -r line; do
			    # Append the contents of each line to /tmp/fzp-playlist
			    echo "$(realpath "$line")" >> /tmp/fzp-playlist
			done <<< "$(echo "$selection")"
		    elif [[ "$mode" == "dirs" ]]; then
			cat /dev/null > /tmp/fzp-playlist
			while IFS= read -r line; do
			    # Append the contents of each line to /tmp/fzp-playlist
			    fd . --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg -e ape "$(realpath "$line")" | sort >> /tmp/fzp-playlist
			done <<< "$(echo "$selection")"
		    fi

		    # Prompt for custom playlist name
		    read -r -e -i "${datetime}" -p "$(echo -e "\033[2mSave tmp playlist to new playlist:\033[0m ")" playlist_name

		    # Check if the name is valid
		    if [[ -z "$playlist_name" ]]; then
			playlist_name="${datetime}"
		    elif [[ "$playlist_name" == *"../"* || "$playlist_name" == *"/.."* ]]; then
			echo -e "\033[31m\nError:\033[0m Invalid name. Escalating into upper folders is not allowed." && sleep 1
			return
		    fi

		    if [[ -f "$HISTORY_DIR/${playlist_name}" ]]; then
			echo -e "\033[31m\nWarning:\033[0m A file with the same name already exists. Overwrite? (y/N):"
			read -r overwrite
			if [[ "$overwrite" != "y" ]]; then
			    echo -e "\033[31m\n\n\nError:\033[0m Operation aborted."
			    continue
			fi
		    fi
		    last=$(cat /tmp/fzp-line)
		    cp /tmp/fzp-playlist "$HISTORY_DIR/${playlist_name}" 2>/dev/null
		    ;;
                add)
                    # Append to /tmp/fzp-playlist without clearing it first or relaunching mpv, i.e., add to queue
                    if [[ "$mode" == "history" ]]; then
			cat "$selection" >> /tmp/fzp-playlist
		    elif [[ "$mode" == "files" ]]; then
			while IFS= read -r line; do
			    # Append the contents of each line to /tmp/fzp-playlist
			    echo "$(realpath "$line")" >> /tmp/fzp-playlist
			done <<< "$(echo "$selection")"
                    elif [[ "$mode" == "dirs" ]]; then
			while IFS= read -r line; do
			    # Append the contents of each line to /tmp/fzp-playlist
			    fd .  --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg -e ape "$(realpath "$line")" | sort >> /tmp/fzp-playlist
			done <<< "$(echo "$selection")"
                    fi
		    last=$(cat /tmp/fzp-line)
                    ;;
                addplay)
                    # Similar to "add" but launch mpv
                    if [[ "$mode" == "history" ]]; then
                        cat "$selection" >> /tmp/fzp-playlist
		    elif [[ "$mode" == "files" ]]; then
			while IFS= read -r line; do
			    # Append the contents of each line to /tmp/fzp-playlist
			    echo "$(realpath "$line")" >> /tmp/fzp-playlist
			done <<< "$(echo "$selection")"
                    elif [[ "$mode" == "dirs" ]]; then
			while IFS= read -r line; do
			    # Append the contents of each line to /tmp/fzp-playlist
			    fd .  --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg -e ape "$(realpath "$line")" | sort >> /tmp/fzp-playlist
			done <<< "$(echo "$selection")"
                    fi
		    last=$(cat /tmp/fzp-line)
                    # head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-pos
		    play_files --playlist=/tmp/fzp-playlist
                    ;;
		shell)
		    if [[ "$mode" == "history" ]]; then
			cd "$HISTORY_DIR"
		    elif [[ "$mode" == "files" ]]; then
			last_selection=$(echo "$selection" | tail -n 1)
			cd "$(realpath "$(dirname "$last_selection")")"
		    elif [[ "$mode" == "dirs" ]]; then
			last_selection=$(echo "$selection" | tail -n 1)
			cd "$(realpath "$last_selection")"
		    fi
		    printf "\033[2m\nPress C-d to return to fzp.\033[0m\n\n"
		    $SHELL
		    cd -
		    last=$(cat /tmp/fzp-line)
		    ;;
		run)
		    read -r -p "$(echo -e "\033[0;0H\033[2mRun command on selection:\033[0m ")" n
		    printf "\n"
                    while IFS= read -r line; do
			eval "$n \"$(realpath "$line")\""
		    done <<< "$(echo "$selection")"
		    printf "\033[2m\nPress return to continue.\033[0m"
		    read -r _
		    last=$(cat /tmp/fzp-line)
		    ;;
                edit)
                    # Invoke $EDITOR on the corresponding $HISTORY_DIR/YYYYMMDD_HHMMSS file
                    # Alternatively, revert to vim
                    # This option is only available while in History fzf prompt
                    if [[ "$mode" == "history" ]]; then
                        eval "${EDITOR:-vim} \"$(realpath "$selection")\""
                    fi
                    ;;
		rename)
		    # Rename or make a copy of the corresponding $HISTORY_DIR/YYYYMMDD_folderdepth2>folderdepth3 file
		    # This option is only available while in History fzf prompt
		    if [[ "$mode" == "history" ]]; then
			current_name=$(basename "$selection")
			printf "\033[2B\033[2m(same name to make a copy, none to abort)\033\0m"
			read -r -e -i "$current_name" -p "$(echo -e "\033[0;0H\033[2mRename '$current_name' to:\033[0m ")" n

			# Check if the new name is valid
			if [[ -z "$n" ]]; then
			    echo -e "\033[31m\n\n\nError:\033[0m Name cannot be empty." && sleep 1
			elif [[ "$n" == *"../"* || "$n" == *"/.."* ]]; then
			    echo -e "\033[31m\n\n\nError:\033[0m Invalid name. Escalating into upper folders is not allowed." && sleep 1
			else
			    new_path="$(realpath -m "$(dirname "$selection")/$n")"

			    if [[ "$new_path" == "$HISTORY_DIR"* ]]; then
				if [[ "$n" == "$current_name" ]]; then
				    datetime=$(date +%Y%m%d_%H%M%S)
				    copy_path="${new_path}_${datetime}_copy"
				    cp -i -v "$selection" "$copy_path"
				else
				    mv -i -v "$selection" "$new_path"
				fi
			    else
				echo -e "\033[31m\n\n\nError:\033[0m Invalid destination path." && sleep 1
			    fi
			fi
		    fi
		    ;;
		delete)
                    # Delete the selected file from history
                    # This option is only available while in History fzf prompt
                    if [[ "$mode" == "history" ]]; then
                        case "$selection" in
			    "$HISTORY_DIR"/tmp)
				echo -e "\033[31m\nWarning:\033[0m The tmp playlist is central to fzp and cannot be deleted."
				sleep 1
				;;
			    *)
				rm -i "$(realpath "$selection")"
				;;
			    esac
                    fi
                    ;;
		cddown)
                    # cd into selected directory and relaunch main()
                    if [[ "$mode" == "dirs" && -n "$(fd . --type d --max-depth 1 "$selection")" ]]; then
                        dir="$(realpath "$selection")"
                        last=""
                    elif [[ "$mode" != "dirs" && -f "$selection" ]]; then
                        from_dir="$dir"
                        dir="$(dirname "$(realpath "$selection")")"
                        last="" # Would be good to calculate the position of the track in the folder here, but it is not "$(tail -n 1 /tmp/fzp-pos)" because this was calculated from the Files view with all brother folders listed
                    elif [[ "$mode" == "dirs" && -z "$(fd . --type d --max-depth 1 "$selection")" ]]; then
                        last="$(tail -n 1 /tmp/fzp-pos)"
                        head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-pos
                    elif [[ "$mode" != "dirs" && -z "$(fd . --type d --max-depth 1)" ]]; then
                        head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-pos
                    elif [[ "$mode" != "dirs" ]]; then
                        from_dir="$dir"
                        dir="$(realpath "$(dirname "$selection")")"
                        last=""
                    fi
                    continue
                    ;;
                cdup)
                    # cd into parent directory and relaunch main()
                    par_dir="$(realpath "$(dirname "$dir")")"
                    if [[ -n "$par_dir" && "$mode" != "files" && "$(realpath "$dir")" != "$(realpath "$media")" ]]; then
                        if [[ "$par_dir" == "$BASE_PATH" || "$par_dir" == "${BASE_PATH}"/* ]]; then
                            dir="$par_dir"
                            last="$(tail -n 1 /tmp/fzp-pos)"
                        else
                            echo "Already at the base path, cannot move up further."
                        fi
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$dir")" != "$(realpath "$media")" ]]; then
                        if [[ "$par_dir" == "$BASE_PATH" || "$par_dir" == "${BASE_PATH}"/* ]]; then
                            case "$dir" in
                                "$from_dir")
                                    dir="$media"
                                    last="" ;;
                                *)
                                    dir="$from_dir"
                                    last="$(tail -n 1 /tmp/fzp-pos)" ;;
                            esac
                        else
                            echo "Already at the base path, cannot move up further."
                        fi
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$dir")" == "$(realpath "$media")" ]]; then
                        last=""
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$from_dir")" == "$(realpath "$media")" ]]; then
                        dir="$media"
                        last="$(tail -n 1 /tmp/fzp-pos)"
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$from_dir")" == "$(realpath "$media")"/* && "$(realpath "$from_dir")" == "$(realpath "$dir")" ]]; then
                        dir="$(realpath "$(dirname "$dir")")"
                        last=""
                    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$from_dir")" == "$(realpath "$media")"/* && "$(realpath "$from_dir")" != "$(realpath "$dir")" ]]; then
                        dir="$from_dir"
                        last="$(tail -n 1 /tmp/fzp-pos)"
                    elif [[ -n "$par_dir" && "$(realpath "$par_dir")" == "$(realpath "$media")"/* && "$(realpath "$par_dir")" != "$(realpath "$dir")" ]]; then
                        dir="$par_dir"
                        last="$(tail -n 1 /tmp/fzp-pos)"
                    fi
                    head -n -1 /tmp/fzp-pos > /tmp/fzp-pos.tmp && mv /tmp/fzp-pos.tmp /tmp/fzp-pos
                    continue
                    ;;
                preview-toggled)
                    # Toggle the preview panel on/off
                    if [[ $(cat /tmp/fzp-preview) == "on" || $(cat /tmp/fzp-preview) == "audio-on" ]]; then 
                        echo "off" > /tmp/fzp-preview
                        fzf_preview=""
                        # pkill mpv
                    else
                        echo "on" > /tmp/fzp-preview
                        case "$mode" in
                            history)
                                fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev" ;;
                            files)
                                fzf_preview="soxi {}" ;;
                            *)
                                fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'" ;;
                        esac
                    fi   
		    last=$(cat /tmp/fzp-line)
                    ;;
                audio-preview)
                    # Enable/disable audio preview
                    if [[ "$audio_preview" == "false" ]]; then
                        fzf_preview='echo -e "\033[5;1m♫\033[25;0m AUDIO PREVIEW\n\n\033[2mPress C-x to stop\033[0m" && sleep 0.2 && mpv --no-config --no-video --really-quiet {}'
                        audio_preview=true
                        echo "audio-on" > /tmp/fzp-preview
                    else
                        audio_preview=false
                        echo "audio-off" > /tmp/fzp-preview
                        case "$(cat /tmp/fzp-preview)" in
                            "on")
                                case "$mode" in
                                    history)
                                        fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev" ;;
                                    files)
                                        fzf_preview="soxi {}" ;;
                                    *)
                                        fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'" ;;
                                esac
                                ;;
                            "off")
                                fzf_preview=""
                                ;;
                            "audio-on")
                                ;;
                            "audio-off")
                                case "$show_help" in
                                    false)
                                    ;;
                                esac
                        esac
                    fi
                    continue
		    last=$(cat /tmp/fzp-line)
                    ;;
		help)
		    # Toggle help display
		    if [[ "$show_help" == "false" ]]; then
			help_text='\033[34;1mKeybindings\033[0m

  General

  \033[1;7m abc \033[0;27m fuzzy search
  \033[1;7m ← → \033[0;27m exit/enter directory
  \033[1;7m ↑ ↓ \033[0;27m move cursor up/down
  \033[1;7m Tab \033[0;27m toggle selection
  \033[1;7m C-q \033[0;27m clear search or quit if none

  Mode

  \033[1;7m C-d \033[0;27m show directories only
  \033[1;7m C-f \033[0;27m show files recursively
  \033[1;7m C-h \033[0;27m show history (playlists)

  Playback queue

  \033[1;7m Ent \033[0;27m make tmp playlist with selection & play
  \033[1;7m C-j \033[0;27m append selection to tmp playlist & resume
  \033[1;7m C-a \033[0;27m append selection to tmp playlist
  \033[1;7m C-s \033[0;27m save tmp playlist to neww playlist

  Miscellaneous

  \033[1;7m   $ \033[0;27m open shell in folder of the last selection
  \033[1;7m C-\ \033[0;27m run command on selection
  \033[1;7m C-o \033[0;27m open current line externally (xdg-open)
  \033[1;7m C-p \033[0;27m toggle preview panel
  \033[1;7m C-x \033[0;27m enable audio preview
  \033[1;7m C-c \033[0;27m disable audio preview
  \033[1;7m   ? \033[0;27m toggle help

  History mode

  \033[1;7m C-e \033[0;27m edit playlist
  \033[1;7m C-r \033[0;27m rename playlist
  \033[1;7m Del \033[0;27m delete playlist

'
			fzf_preview="printf '$help_text'"
			show_help=true
		    else
			show_help=false
			case "$(cat /tmp/fzp-preview)" in
			    "on")
				case "$mode" in
				    history)
					fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev" ;;
				    files)
					fzf_preview="soxi {}" ;;
				    *)
					fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'" ;;
				esac
				;;
			    "off")
				fzf_preview=""
				;;
			    "audio-on")
				fzf_preview='echo -e "\033[5;1m♫\033[25;0m AUDIO PREVIEW\n\n\033[2mPress C-x to stop\033[0m" && sleep 0.2 && mpv --no-config --no-video --really-quiet {}'
				;;
			esac
		    fi
		    last=$(cat /tmp/fzp-line)
		    ;;
                quit)
                    # Quit the program
                    pkill -P $$
		    clear
                    return
                    ;;
                *)
                    continue
                    ;;
            esac
        fi
    done
}   

make_lua_script() {
    # Check if the Lua script already exists and has the hash of the last version
    if [[ ! -f "$CONFIG_DIR/fzp.lua" || "$(sha256sum "$CONFIG_DIR"/fzp.lua)" != "6446e67bfe943b3cbf67a5d74e159f72909db4023810d7ef4f4673748aed5a5e" ]]; then

        # Write the Lua script to "$CONFIG_DIR/fzp.lua"
        cat << 'EOF' > "$CONFIG_DIR/fzp.lua"
local mp = require 'mp'
local utils = require 'mp.utils'

-- Variables to track visibility states
local show_keybindings = false
local show_playlist = true

-- Function to get the current folder name and its parent directory
local function get_current_and_parent_folder()
    local path = mp.get_property("path")
    if path then
        path = path:gsub("'", "'\\''")
        local folder_path = path:match("(.*/)")
        if folder_path then
            local current_folder = folder_path:match("([^/]+)/$")
            local parent_folder_path = folder_path:match("(.*/)[^/]+/$")
            local parent_folder = parent_folder_path and parent_folder_path:match("([^/]+)/$")
            if current_folder and parent_folder then
                return parent_folder .. "/" .. current_folder
            elseif current_folder then
                return current_folder
            end
        end
    end
    return "Unknown"
end

-- Function to get the playlist lines using mpv's property
local function get_playlist_lines()
    local playlist = mp.get_property_native('playlist')
    local lines = {}
    for _, item in ipairs(playlist) do
        table.insert(lines, item.title or item.filename)
    end
    return lines
end

-- Function to print the rolling playlist
local function print_rolling_playlist(lines, current_index)
    local num_files = #lines
    local start_index = math.max(1, current_index - 4)
    local end_index = math.min(num_files, start_index + 9)
    
    local formatted_output = ""
    if start_index > 1 then
        formatted_output = formatted_output .. string.format("  \\033[30m↑ (%d hidden items)\\033[0m\n", start_index - 1)
    end
    for i = start_index, end_index do
        local prefix = (i == current_index) and "  \\033[37m●\\033[0m " or "  ○ "
        formatted_output = formatted_output .. prefix .. "\\033[2m" .. lines[i] .. "\\033[0m\n"
    end
    if end_index < num_files then
        formatted_output = formatted_output .. string.format("  \\033[30m↓ (%d hidden items)\\033[0m\n", num_files - end_index)
    elseif end_index == num_files and num_files > 10 then
        formatted_output = formatted_output .. "  \\033[30m…\\033[0m\n"
    end

    return formatted_output
end

-- Function to get the current file index
local function get_current_file_index(lines)
    local current_file = mp.get_property("media-title")
    if not current_file then
        return 1
    end
    for i, line in ipairs(lines) do
        if line:find(current_file, 1, true) then
            return i
        end
    end
    return 1
end

-- Function to print the playlist, keybindings, and additional message
local function print_playlist_and_keybindings()
    -- Get the playlist lines
    local lines = get_playlist_lines()
    local current_index = get_current_file_index(lines)
    local num_files = #lines

    -- Get the rolling playlist output
    local playlist_output = print_rolling_playlist(lines, current_index)

    -- Get the current and parent folder name
    local current_and_parent_folder = get_current_and_parent_folder()

    -- Formatted message
    local playing_message = string.format("printf '\\033[36mPlaying %s (%d on %d file(s))\\033[0m\n\n'", current_and_parent_folder, current_index, num_files)

    -- Keybindings
    local keybindings = [[
printf '\033[36mKeybindings:\033[0m

  \033[1;7m  space \033[0;27m  \033[2mplay/pause \033[0m                \033[1;7m     l \033[0;27m  \033[2mA/B loop \033[0m
  \033[1;7m    ← → \033[0;27m  \033[2mseek -5/+5 seconds \033[0m        \033[1;7m     v \033[0;27m  \033[2mtoggle .lrc lyrics \033[0m
  \033[1;7m    ↑ ↓ \033[0;27m  \033[2mseek -60/+60 seconds \033[0m      \033[1;7m     P \033[0;27m  \033[2mtoggle playlist \033[0m
  \033[1;7m [ ] ⌫  \033[0;27m  \033[2mdec/inc/reset speed \033[0m       \033[1;7m     M \033[0;27m  \033[2mtoggle minimal TUI \033[0m
  \033[1;7m    < > \033[0;27m  \033[2mprev/next track \033[0m           \033[1;7m     _ \033[0;27m  \033[2mtoggle cover art \033[0m
  \033[1;7m      L \033[0;27m  \033[2mrepeat track \033[0m              \033[1;7m     ? \033[0;27m  \033[2mtoggle help   \033[0m
  \033[1;7m  9 0 m \033[0;27m  \033[2mvol-/vol+/mute \033[0m            \033[1;7m     q \033[0;27m  \033[2mstop and go to browser \033[0m

'
]]

    -- Clear the terminal
    mp.command('run clear')

    -- Conditionally print the keybindings
    if show_keybindings then
        os.execute(keybindings)
    else
        os.execute('printf "\\033[2m? Help\\033[27;0m\n\n"')
    end
    
    -- Print the playing message
    os.execute(playing_message)
    
    -- Conditionally print the playlist
    if show_playlist then
        local playlist_output_cmd = string.format('printf "%s"', playlist_output)
        os.execute(playlist_output_cmd)
        io.write("\n") -- Add an empty line after the playlist output
    end
end

-- Function to toggle the screen state between mpv and fzf
local screen_toggled = false
local function toggle_all()
    if screen_toggled then
        print_playlist_and_keybindings()
        screen_toggled = false
    else
        mp.command('run clear')
        mp.command_native({"script-message", "osc", "no-osd"})
        screen_toggled = true
    end
end

-- Function to toggle keybindings display
local function toggle_help()
    show_keybindings = not show_keybindings
    print_playlist_and_keybindings()
end

-- Function to toggle playlist display
local function toggle_playlist()
    show_playlist = not show_playlist
    print_playlist_and_keybindings()
end

-- Register event to clear the terminal and print playlist, keybindings, and additional message on end-file
mp.register_event('end-file', function()
    print_playlist_and_keybindings()
end)

-- Register event to clear the terminal and print playlist, keybindings, and additional message on file-loaded
mp.register_event('file-loaded', function()
    print_playlist_and_keybindings()
end)

-- Determine the playlist file path at the beginning
local initial_playlist_file = mp.get_property("playlist")
local filepath = "/tmp/fzp-playlist"

-- If an initial playlist file was provided, use that for monitoring
if initial_playlist_file and initial_playlist_file:match("^/") then
    filepath = initial_playlist_file
end

-- Initialize last_mtime with the current modification time of the playlist file to avoid unnecessary interruption on startup
local function initialize_last_mtime()
    local file_info = utils.file_info(filepath)
    if file_info then
        last_mtime = file_info.mtime
    end
end

initialize_last_mtime()

-- Function to check and reload the playlist if it has changed
local function check_and_reload_playlist()
    local file_info = utils.file_info(filepath)
    if file_info then
        local mtime = file_info.mtime
        if last_mtime == nil or mtime > last_mtime then
            last_mtime = mtime

            -- Save the current playback position and file
            local current_position = mp.get_property_number("time-pos", 0)
            local current_file = mp.get_property("path")

            -- Load the new playlist
            mp.commandv("loadlist", filepath, "replace")

            -- Find the index of the current file in the new playlist
            local function resume_playback()
                if current_file then
                    local playlist = mp.get_property_native("playlist")
                    local current_index = nil
                    for i, item in ipairs(playlist) do
                        if item.filename == current_file then
                            current_index = i - 1
                            break
                        end
                    end

                    -- If the current file is in the new playlist, resume playback from the saved position
                    if current_index then
                        mp.set_property_number("playlist-pos", current_index)
                        mp.commandv("seek", current_position, "absolute", "exact")
                    end
                end
            end

            -- Use a deferred call to ensure the playlist is fully loaded before seeking
            mp.add_timeout(0.1, resume_playback)

            -- Print updated playlist and keybindings
            print_playlist_and_keybindings()
        end
    end
end

-- Periodically check the playlist for changes
mp.add_periodic_timer(1, check_and_reload_playlist)

-- Add keybindings to toggle the screen state, keybindings, and playlist
mp.add_key_binding("M", "toggle-all", toggle_all)
mp.add_key_binding("?", "toggle-keybindings", toggle_help)
mp.add_key_binding("P", "toggle-playlist", toggle_playlist)
EOF
    fi
}

# Main script logic
check_dependencies
make_lua_script
clear
parse_args "$@"
configure_mpv_interface

case "$mode" in
    history)
	multi="--no-multi"
        filter="--type f"
        filter2="."
        fzf_prompt='History > '
        fzf_preview="printf 'Tracks: ' && wc -l < {} && printf '\n' && cat -n {} | rev | cut -d / -f -2 | rev"
        fzf_preview_window="45%,border-left,nowrap"
        fzf_header='
? Help

'
        main "$HISTORY_DIR"
        ;;
    files)
	multi="--multi"
        filter='--type f'
        filter2='--max-depth 8 -e mp3 -e m4a -e flac -e wav -e ogg -e ape'
        fzf_prompt='Files > '
        fzf_preview="soxi {}"
        fzf_preview_window="45%,border-left,nowrap"
        fzf_header='
? Help

'
        main "$path"
        ;;
    ""|dirs)
	multi="--multi"
        mode="dirs"
        filter='--type d'
        filter2="."
        fzf_prompt="Dirs > "
        fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'"
        fzf_preview_window="45%,border-left,nowrap"
        fzf_header='
? Help

'
        main "$path"
        ;;
esac
