#!/usr/bin/env bash

#### Configuration ##############################################################
# Folders
media="$HOME/Music/"
CONFIG_DIR="$HOME/.config/fzplayer"
HISTORY_DIR="$CONFIG_DIR/history" # Rename to history later

# Set default playback interface: one of "text", "sixel" or "gui"
interface="text"

# Set alternate playback interface (_ key): one of "sixel" or "gui", only used when the primary is "text"
secondary_interface="sixel"

# Show the history in the text interface. Note that mpv versions < 0.38.0 will show
# some garbled characters before the non-playing entries, hardcoded by the OSD
# (see https://github.com/mpv-player/mpv/issues/5868)
# Values are one of "yes" or "no"; if set to "no", F8 will show the list temporarily.
persistent_terminal_playlist="no"

# Use supplied lua script to format output
luascript="yes"
#### End of configuration #######################################################

# Variables
if [ "$persistent_terminal_playlist" = "yes" ]; then
    text_playlist="\n\${playlist}"
    # echo "mp.register_event('end-file', function() mp.command('run clear') end)" > /tmp/fzplayerlua
else
    text_playlist=""
    # cat /dev/null > /tmp/fzplayer.lua
fi

if [ "$luascript" = "yes" ]; then
    script="--script=$CONFIG_DIR/fzplayer.lua"
fi

text_status="'\${?pause==no:▶ }\${?pause==yes:⏸ }\${percent-pos}% [\${time-pos}/\${duration}] \${filename} \${?pause==yes:(paused)}\n$text_playlist '"
mpv_opts="--no-config --ao=pulse $script --watch-later-dir=$HOME/.local/state/mpv/watch_later --save-position-on-quit --script-opts=osc-visibility=always --msg-level=all=error,statusline=status --term-status-msg=$text_status"

mode=""
path=""
dummy_text="'$(printf \\033)'"
show_help=false
audio_preview=false

case "$interface" in
    text)
	if [ "$secondary_interface" = "gui" ]; then
	    secondary_interface="gui" # ""
	fi
	mpvui="--vo=$secondary_interface --no-video --input-conf='memory://_ cycle-values term-status-msg $dummy_text ${text_status//\'/\"}; cycle vid'"
	echo "$mpvui" > /tmp/fzplayer-mpv.conf
	;;
    sixel)
	mpvui="--vo=sixel --input-conf='memory://_ cycle-values term-status-msg $dummy_text ${text_status//\'/\"}; cycle vid'"
	echo "$mpvui" > /tmp/fzplayer-mpv.conf
        ;;
    gui)
	mpvui="--input-conf='memory://_ cycle vid'"
	echo "--no-video" > /tmp/fzplayer-mpv.conf
	echo "$mpvui" >> /tmp/fzplayer-mpv.conf
        ;;
    *)
        echo "Error: Invalid value for --interface. Use one of (text, sixel, gui)"
        exit 1
        ;;
esac
sed -i 's|--|\n--|g' /tmp/fzplayer-mpv.conf


# Create necessary directories if they don't exist
mkdir -p "$HISTORY_DIR"

# Function to display help menu
show_help() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  -c, --continue           Resume playback from history"
    echo "  -f, --files              List audio files instead of directories"
    echo "  -i, --interface <value>  Set primary playback interface (text, sixel, gui)"
    echo "  -p, --path <path>        Set path to media"
    echo "  -h, --help               Show this help message and exit"
}

# Function to parse command-line arguments
parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            -h|--help)
                show_help
                exit 0
                ;;
            -c|--continue)
                mode="continue"
                ;;
            -f|--files)
                mode="files"
                ;;
            -i|--interface)
                shift
                if [ -z "$1" ]; then
                    echo "Error: --interface requires a value (none, sixel, gui)"
                    exit 1
                fi
                case "$1" in
		    text)
			if [ "$secondary_interface" = "gui" ]; then
			    secondary_interface="gui" # ""
			fi
			mpvui="--vo=$secondary_interface --no-video --input-conf='memory://_ cycle-values term-status-msg $dummy_text ${text_status//\'/\"}; cycle vid'"
			;;
		    sixel)
			mpvui="--vo=sixel --input-conf='memory://_ cycle-values term-status-msg $dummy_text ${text_status//\'/\"}; cycle vid'"
			;;
		    gui)
			mpvui="--input-conf='memory://_ cycle vid'"
			;;
		    *)
                esac
                ;;
            -p|--path)
                shift
                if [ -z "$1" ]; then
                    echo "Warning: --path requires a value. Using default"
                    path=$(realpath "$media")
                else
                    path=$(realpath "$1")
                fi
                ;;
            *)
                echo "Error: Invalid option $1"
                show_help
                exit 1
                ;;
        esac
        shift
    done

    # Set default path if not provided
    if [ -z "$path" ]; then
        path=$(realpath "$media")
    fi
}

# Function to play selected files
play_files="mpv $mpv_opts $mpvui" # We have to use an eval of $play_files here because this allows using double quotes; if we make a function instead, then the $mpv_opts and $mpvui are not correctly expanded, even with double quotes

# Basic file browser with directory and file preview
fdfun() {
    fd $filter --min-depth 1 --max-depth 1 -L $filter2 --color=always | sort
}

# Main function
# issues:
# - flicker due to loop: cannot be solved?
# - edit playlist
# - save playlist
main() {
    
    echo "$HISTORY_DIR" > /tmp/fzplayer-dirs
    cd "$1" 2>/dev/null || { echo "Invalid media directory: '$1'"; exit 1; }
    echo "$1" >> /tmp/fzplayer-dirs

    cat /dev/null > /tmp/fzplayer-playlist
    cat /dev/null > /tmp/fzplayer-pos
    echo "on" > /tmp/fzplayer-preview

    while :; do

	if [[ -z "$dir" ]]; then
	    dir="$media"
	elif [[ -f "$dir" ]]; then
	    dir="$(dirname "$dir")"
	fi
	cd "$dir"
	
	folder="$(basename "$dir" )"

	clear

	selection=$(fdfun \
			| fzf --query="${tmp}" \
			      --prompt='# ' \
			      --ansi \
			      --extended \
			      --no-border \
			      --delimiter='/' \
			      --layout=reverse-list \
			      --no-multi \
			      --cycle \
			      --sync \
			      --prompt="$(printf '%s\033[2m%s > \033[0m' "$fzf_prompt" "$folder")" \
			      --header="$fzf_header" \
			      --preview="$fzf_preview" \
			      --preview-window="$fzf_preview_window" \
			      --with-nth="$fzf_withnth.." \
			      --margin='1,2,1,2' \
			      --color='16,gutter:-1' \
			      --info-command='echo -e "\x1b[33;1m$FZF_POS\x1b[m/$FZF_INFO"' \
			      --bind="start:pos($last)" \
			      --bind='enter:execute-silent(echo "$FZF_POS" >> /tmp/fzplayer-pos)' \
			      --bind='enter:+execute(echo "play" > /tmp/fzplayer-arg)+accept' \
			      --bind='?:execute(echo "help" > /tmp/fzplayer-arg)+accept' \
			      --bind='ctrl-p:execute(echo "preview-toggled" > /tmp/fzplayer-arg)+accept' \
			      --bind='ctrl-h:execute(echo "history" > /tmp/fzplayer-arg)+accept' \
                              --bind='ctrl-d:execute(echo "dirs" > /tmp/fzplayer-arg)+accept' \
			      --bind='ctrl-f:execute(echo "files" > /tmp/fzplayer-arg)+accept' \
                              --bind='ctrl-e:execute(echo "edit" > /tmp/fzplayer-arg)+accept' \
			      --bind='ctrl-a:execute(echo "add" > /tmp/fzplayer-arg)+accept' \
			      --bind='left:execute(echo "cdup" > /tmp/fzplayer-arg)+accept' \
			      --bind='right:execute-silent(echo "$FZF_POS" >> /tmp/fzplayer-pos)' \
			      --bind='right:+execute(echo "cddown" > /tmp/fzplayer-arg)+accept' \
			      --bind='ctrl-x:execute(echo "audio-preview" > /tmp/fzplayer-arg)+accept' \
			      --bind='ctrl-c:execute(echo "preview-toggled" > /tmp/fzplayer-arg)+accept' \
                              --bind='ctrl-q:execute(echo "quit" > /tmp/fzplayer-arg)+cancel' \
                              --bind='esc:execute(echo "quit" > /tmp/fzplayer-arg)+cancel')

	if [[ -f "/tmp/fzplayer-arg" ]]; then
            arg=$(cat /tmp/fzplayer-arg)
            rm /tmp/fzplayer-arg
        else
            arg="ls -lah"
        fi

        if [[ -f "/tmp/fzplayer-last" ]]; then
            last_selection=$(cat /tmp/fzplayer-last)
            rm /tmp/fzplayer-last
        fi

        if ! [[ -v "$selection" ]]; then
            clear
            case "$arg" in
                history)
		    mode="continue"
		    filter="--type f"
		    filter2=". $HISTORY_DIR"
		    fzf_prompt='History > '
		    fzf_withnth="-1"
		    if [[ $(cat /tmp/fzplayer-preview) == "on" ]]; then 
			fzf_preview="cat {} | rev | cut -d / -f -2 | rev"
		    fi
		    fzf_preview_window="45%,border-left,nowrap"
		    fzf_header='
? Help

'
                    continue
                    ;;
                dirs)
		    mode="dirs"
		    filter='--type d'
		    filter2="."
		    fzf_prompt="Dirs > "
		    fzf_withnth="-3"
		    if [[ $(cat /tmp/fzplayer-preview) == "on" ]]; then 
			fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'"
		    fi
		    fzf_preview_window="45%,border-left,nowrap"
		    fzf_header='
? Help

'
                    continue
                    ;;
		files)
		    mode="files"
		    filter='--type f'
		    filter2='--max-depth 8 -e mp3 -e m4a -e flac -e wav -e ogg'
		    fzf_prompt='Files > '
		    fzf_withnth="-3"
		    if [[ $(cat /tmp/fzplayer-preview) == "on" ]]; then 
			fzf_preview="soxi {}"
		    fi
		    fzf_preview_window="45%,border-left,nowrap"
		    fzf_header='
? Help

'
		    continue
		    ;;
                play)
		    # fd the list of audio files in subdirectories of the selected folder and list them with their full path in /tmp/fzplayer-playlist
		    # Then run play_files on that list
		    if [[ "$mode" != "continue" ]]; then
			fd .  --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg "$(realpath "$selection")" | sort > /tmp/fzplayer-playlist
		    else
			cp "$selection" /tmp/fzplayer-playlist
		    fi
		    last="$(tail -n 1 /tmp/fzplayer-pos)"
		    head -n -1 /tmp/fzplayer-pos > /tmp/fzplayer-pos.tmp && mv /tmp/fzplayer-pos.tmp /tmp/fzplayer-pos
		    eval "$play_files --playlist=/tmp/fzplayer-playlist" # We have to use an eval of $play_files here because this allows using double quotes; if we make a function instead, then the $mpv_opts and $mpvui are not correctly expanded, even with double quotes
                    ;;
		add)
		    # Similar to "play" but append to /tmp/fzplayer-playlist without relaunching mpv, i.e., add to queue
		    fd .  --type f --min-depth 1 --max-depth 8 -L -e mp3 -e m4a -e flac -e wav -e ogg "$(realpath "$selection")" | sort >> /tmp/fzplayer-playlist
		    ;;
		save)
		    # Save current /tmp/fzplayer-playlist playlist to $HISTORY_DIR/YYYYMMDD_<number of lines in the file>_tracks
		    local datetime=$(date +%Y%m%d_%H%M%S)
		    local lines=$(wc -l < /tmp/fzplayer-playlist)
		    cp /tmp/fzplayer-playlist "$HISTORY_DIR/${datetime}_${lines}_tracks"
		    ;;
                edit)
		    # Invoke $EDITOR on the corresponding $HISTORY_DIR/YYYYMMDD_folderdepth2>folderdepth3 file
		    # Alternatively, revert to vim
		    # This option is only available while in History fzf prompt
		    if [ "$mode" == "continue" ]; then
		        local file_to_edit=$(ls -t "$HISTORY_DIR" | fzf --prompt="Select playlist to edit > ")
		        [ -n "$file_to_edit" ] && ${EDITOR:-vim} "$HISTORY_DIR/$file_to_edit"
		    fi
                    ;;
                cddown)
		    # cd into selected directory and relaunch main()
                    if [[ "$mode" == "dirs" && -n "$(fd . --type d --max-depth 1 "$selection")" ]]; then
			dir="$(realpath "$selection")"
			last=""
		    elif [[ "$mode" != "dirs" && -f "$selection" ]]; then
			from_dir="$dir"
			dir="$(dirname "$(realpath "$selection")")"
			last="" # Would be good to calculate the position of the track in the folder here, but it is not "$(tail -n 1 /tmp/fzplayer-pos)" because this was calculated from the Files view with all brother folders listed
		    elif [[ "$mode" == "dirs" && -z "$(fd . --type d --max-depth 1 "$selection")" ]]; then
			last="$(tail -n 1 /tmp/fzplayer-pos)"
			head -n -1 /tmp/fzplayer-pos > /tmp/fzplayer-pos.tmp && mv /tmp/fzplayer-pos.tmp /tmp/fzplayer-pos
		    elif [[ "$mode" != "dirs" && -z "$(fd . --type d --max-depth 1)" ]]; then
			head -n -1 /tmp/fzplayer-pos > /tmp/fzplayer-pos.tmp && mv /tmp/fzplayer-pos.tmp /tmp/fzplayer-pos
		    elif [[ "$mode" != "dirs" ]]; then
			from_dir="$dir"
			dir="$(realpath "$(dirname "$selection")")"
			last=""
		    fi
		    continue
                    ;;
                cdup)
		    # cd into parent directory and relaunch main()
		    par_dir="$(realpath "$(dirname "$dir")")"
		    if [[ -n "$par_dir" && "$mode" != "files" && "$(realpath "$dir")" != "$(realpath "$media")" ]]; then
			dir="$par_dir"
			last="$(tail -n 1 /tmp/fzplayer-pos)"
		    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$dir")" != "$(realpath "$media")" ]]; then
			case "$dir" in
			    "$from_dir")
				dir="$media"
				last=""	;;
			    *)
				dir="$from_dir"
				last="$(tail -n 1 /tmp/fzplayer-pos)" ;;
			esac
		    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$dir")" == "$(realpath "$media")" ]]; then
			last=""
		    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$from_dir")" == "$(realpath "$media")" ]]; then
			dir="$media"
			last="$(tail -n 1 /tmp/fzplayer-pos)"
		    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$from_dir")" == "$(realpath "$media")"/* && "$(realpath "$from_dir")" == "$(realpath "$dir")" ]]; then
			dir="$(realpath "$(dirname "$dir")")"
			last=""
		    elif [[ -n "$par_dir" && "$mode" == "files" && "$(realpath "$from_dir")" == "$(realpath "$media")"/* && "$(realpath "$from_dir")" != "$(realpath "$dir")" ]]; then
			dir="$from_dir"
			last="$(tail -n 1 /tmp/fzplayer-pos)"
		    elif [[ -n "$par_dir" && "$(realpath "$par_dir")" == "$(realpath "$media")"/* && "$(realpath "$par_dir")" != "$(realpath "$dir")" ]]; then
			dir="$par_dir"
			last="$(tail -n 1 /tmp/fzplayer-pos)"
		    fi
		    head -n -1 /tmp/fzplayer-pos > /tmp/fzplayer-pos.tmp && mv /tmp/fzplayer-pos.tmp /tmp/fzplayer-pos
                    continue
                    ;;
                preview-toggled)
		    if [[ $(cat /tmp/fzplayer-preview) == "on" || $(cat /tmp/fzplayer-preview) == "audio-on" ]]; then 
                        echo "off" > /tmp/fzplayer-preview
			fzf_preview=""
			pkill mpv
                    else
                        echo "on" > /tmp/fzplayer-preview
			case "$mode" in
			    continue)
				fzf_preview="cat {} | rev | cut -d / -f -2 | rev" ;;
			    files)
				fzf_preview="soxi {}" ;;
			    *)
				fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'" ;;
			esac
                    fi   
		    continue
                    ;;
		audio-preview)
		    if [[ "$audio_preview" == "false" ]]; then
			fzf_preview='echo -e "\033[5;1m♫\033[25;0m AUDIO PREVIEW\n\n\033[2mPress C-x to stop\033[0m" && sleep 0.2 && mpv --no-config --no-video --really-quiet {}'
			audio_preview=true
			echo "audio-on" > /tmp/fzplayer-preview
		    else
			audio_preview=false
			echo "audio-off" > /tmp/fzplayer-preview
			case "$(cat /tmp/fzplayer-preview)" in
                            "on")
				case "$mode" in
                                    continue)
					fzf_preview="cat {} | rev | cut -d / -f -2 | rev" ;;
                                    files)
					fzf_preview="soxi {}" ;;
                                    *)
					fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'" ;;
				esac
				;;
                            "off")
				fzf_preview=""
				;;
			    "audio-on")
				;;
			    "audio-off")
				case "$show_help" in
				    false)
				    ;;
				esac
			esac
                    fi
		    continue
		    ;;
#					      --bind='ctrl-x:change-preview(echo -e "\033[5;1m♫\033[25;0m AUDIO PREVIEW\n\n\033[2mPress C-c to stop\033[0m" && mpv --no-config --no-video --really-quiet {})+refresh-preview' \
		help)
		    if [[ "$show_help" == "false" ]]; then
			help_text='\033[34;1mKeybindings\033[0m

  General

  \033[1;7m abc \033[0;27m fuzzy search
  \033[1;7m ← → \033[0;27m exit/enter directory
  \033[1;7m ↑ ↓ \033[0;27m move cursor up/down
  \033[1;7m Ent \033[0;27m create playlist from selection and play
  \033[1;7m C-q \033[0;27m clear search or quit

  Mode

  \033[1;7m C-d \033[0;27m show directories only
  \033[1;7m C-f \033[0;27m show files recursively
  \033[1;7m C-h \033[0;27m show history (past playlists to resume)

  Preview

  \033[1;7m C-p \033[0;27m toggle preview panel
  \033[1;7m C-x \033[0;27m enable audio preview
  \033[1;7m C-c \033[0;27m disable audio preview
  \033[1;7m   ? \033[0;27m toggle help

  History

  \033[1;7m C-e \033[0;27m edit playlist
  \033[1;7m Del \033[0;27m delete playlist

'
			fzf_preview="printf '$help_text'"
			show_help=true
                    else
			show_help=false
			case "$(cat /tmp/fzplayer-preview)" in
                            "on")
				case "$mode" in
                                    continue)
					fzf_preview="cat {} | rev | cut -d / -f -2 | rev" ;;
                                    files)
					fzf_preview="soxi {}" ;;
                                    *)
					fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'" ;;
				esac
				;;
                            "off")
				fzf_preview=""
				;;
                            "audio")
				fzf_preview=""
				;;
			esac
                    fi
                    continue
                    ;;
		quit)
                    pkill -P $$
                    return
                    ;;
                *)
		    continue
                    ;;
            esac
        fi
    done
}	

# Main script logic
clear
parse_args "$@"

case "$mode" in
    continue)
        filter="--type f"
        filter2="."
        fzf_prompt='History > '
        fzf_preview="cat {} | rev | cut -d / -f -2 | rev"
        fzf_preview_window="45%,border-left,nowrap"
        fzf_header='
? Help
'
        main "$HISTORY_DIR" "$mode"
        ;;
    files)
        filter='--type f'
        filter2='-e mp3 -e m4a -e flac -ewav -e ogg'
        fzf_prompt='Files > '
	fzf_preview="soxi {}"
        fzf_preview_window="45%,border-left,nowrap"
        fzf_header='
? Help

'
        main "$path" "$mode"
        ;;
    *)
        mode="dirs"
        filter='--type d'
        filter2="."
        fzf_prompt="Dirs > "
        fzf_preview="tree -C {} | sed 's/[│├─└]/ /g'"
        fzf_preview_window="45%,border-left,nowrap"
        fzf_header='
? Help

'
        main "$path" "$mode"
        ;;
esac








###
# Old function
fzf_browser() {
    local dir="1"
    local mode="$2"
    
    cd "$HISTORY_DIR" || { echo "Invalid history directory: '$HISTORY_DIR'"; exit 1; }
    cd "$dir" || { echo "Invalid media directory: '$dir'"; exit 1; }

    echo "$HISTORY_DIR" > /tmp/fzplayer-dirs
    echo "$dir" >> /tmp/fzplayer-dirs

    cat /dev/null > /tmp/fzplayer-playlist
    cat /dev/null > /tmp/fzplayer-playlist-name
    cat /dev/null > /tmp/fzplayer-arg
    
    # Modified bind action to handle both directories and files
    list | sort | sed 's|^\./||' | fzf --ansi --sync --multi --height=100% --border=none --delimiter="/" --with-nth=-2..-1 \
    --prompt="$fzf_prompt" \
    --header="$fzf_header" \
    --preview="$fzf_preview" \
    --preview-window="$fzf_preview_window" \
    --bind="enter:execute(
        echo {} | sed 's|/| > |g' > /tmp/fzplayer-playlist-name && \
        (if [ -d {} ]; then \
            fd . --min-depth 1 --max-depth 5 --type f -e mp3 -e m4a -e flac -e wav -e ogg $(realpath {}) | sort | sed 's|^\./||'; \
        else \
            echo {} | sed 's|^\./||'; \
        fi) > /tmp/fzplayer-playlist && \
	clear && printf '\033[34mPlaying %s (%s file(s)):\033[0m\n\n' {} $(wc -l < /tmp/fzplayer-playlist) && \
        head /tmp/fzplayer-playlist -n 40 | rev | cut -d / -f 1 | rev | sed 's|^|  |' | column -c $(tput cols) -x && printf '\n' && \
	printf '\033[34m\nKeybindings:\033[0m\n\n  q: stop playback and go back\n  space: play/pause\n  arrows: seek\n  </>: prev/next in playlist\n  9/0/m: vol-/vol+/mute\n  F8: show playlist\n  _: toggle graphical interface (sixel or gui, as set in configuration or at runtime)\n\n' & \
        mpv $mpv_opts $mpvui --playlist=/tmp/fzplayer-playlist)" \
    --bind='ctrl-x:+change-preview(echo -e "\033[5;1m♫\033[25;0m AUDIO PREVIEW\n\n\033[2mPress C-c to stop\033[0m" && mpv --no-config --no-video --really-quiet {})' \
    --bind='ctrl-x:+change-preview-window(45%,border-left,nowrap)' \
    --bind='ctrl-x:+refresh-preview' \
    --bind='ctrl-c:execute-silent(pkill play)' \
    --bind='ctrl-c:+change-preview(tree -C {} | sed 's/[│├─└]/ /g')' \
    --bind='ctrl-c:+refresh-preview' \
    --bind='ctrl-d:change-prompt(Directories > )' \
    --bind='ctrl-d:+reload(fd . --min-depth 1 --max-depth 1 --type d $(tail /tmp/fzplayer-dirs -n 1) | sort | sed "s|^\./||")' \
    --bind='ctrl-d:+change-preview(tree -C {} | sed 's/[│├─└]/ /g')' \
    --bind='ctrl-d:+change-preview-window(45%,border-left,nowrap)' \
    --bind='ctrl-d:+refresh-preview' \
    --bind='ctrl-f:change-prompt(Files > )' \
    --bind='ctrl-f:+reload(fd . --min-depth 1 --max-depth 5 --type f --color=always -e mp3 -e m4a -e flac -e wav -e ogg $(tail /tmp/fzplayer-dirs -n 1) | sort | sed "s|^\./||")' \
    --bind='ctrl-f:+change-preview(printf \\033[34m{} | sed "s|$(tail -n 1 /tmp/fzplayer-dirs)/||" | xargs -I {} dirname {} && printf \\033[0m && soxi {})' \
    --bind='ctrl-f:+change-preview-window(45%,border-left,nowrap)' \
    --bind='ctrl-f:+refresh-preview' \
    --bind='ctrl-delete:execute(rm -i {})+reload(fd --min-depth 1 --max-depth 1 --type f $(head /tmp/fzplayer-dirs -n 1) | sort)' \
    --bind='ctrl-h:change-prompt(History > )' \
    --bind='ctrl-e:execute(echo 'edit' > /tmp/fzplayer-arg {})' \
    --bind='ctrl-h:+reload(fd . --min-depth 1 --max-depth 1 --type f $(head /tmp/fzplayer-dirs -n 1) | sort)' \
    --bind='ctrl-h:+change-preview(cat {} | rev | cut -d / -f -2 | rev)' \
    --bind='ctrl-h:+change-preview-window(45%,border-left,nowrap)' \
    --bind='ctrl-h:+refresh-preview' \
    --bind='ctrl-h:+change-header(
C-d: display directories        C-e: edit playlist
C-f: display files              Del: delete playlist 
C-p: toggle preview panel
Tab: select
C-a: select all
C-w: deselect all
Ent: play selection as a playlist (main action)

)' \
    --bind='ctrl-d:+change-header(
C-f: display files
C-h: display history
C-p: toggle preview panel
Tab: select
C-a: select all
C-w: deselect all
Ent: play selection as a playlist (main action)

)' \
    --bind='ctrl-f:+change-header(
C-d: display directories        C-x: enable audio preview
C-h: display history            C-c: disable audio preview
C-p: toggle preview panel
Tab: select
C-a: select all
C-w: deselect all
Ent: play selection as a playlist (main action)

)' \
    --bind='ctrl-a:select-all' \
    --bind='ctrl-w:deselect-all' \
    --bind='ctrl-p:toggle-preview'
}
